In [1]:
!pip install scikit-learn

   ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.9 MB 1.7 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/8.9 MB 1.5 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/8.9 MB 1.5 MB/s eta 0:00:06
   ----- ---------------------------------- 1.3/8.9 MB 1.5 MB/s eta 0:00:05
   -------- ------------------------------- 1.8/8.9 MB 1.7 MB/s eta 0:00:05
   ---------- ----------------------------- 2.4/8.9 MB 1.8 MB/s eta 0:00:04
   ----------- ---------------------------- 2.6/8.9 MB 1.8 MB/s eta 0:00:04
   -------------- ------------------------- 3.1/8.9 MB 1.9 MB/s eta 0:00:04
   ---------------- ----------------------- 3.7/8.9 MB 2.0 MB/s eta 0:00:03
   ------------------- -------------------- 4.5/8.9 MB 2.1 MB/s eta 0:00:03
   ----------------------- ---------------- 5.2/8.9 MB 2.3 MB/s eta 0:00:02
   -----------------------

In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
X,y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [4]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [5]:
X = torch.tensor(X,dtype=torch.float32)
y = torch.tensor(y,dtype=torch.long)

In [6]:
from torch.utils.data import Dataset,DataLoader

In [7]:
class CustomDataset(Dataset):

    def __init__(self,features,labels):

        self.features = features
        self.labels = labels

    def __len__(self):

        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index],self.labels[index]
        

In [8]:
dataset = CustomDataset(X,y)

In [9]:
len(dataset)

10

In [10]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

In [11]:
for batch_features,batch_labels in dataloader:

    print(batch_features)
    print(batch_labels)
    print("-"*50)

tensor([[ 1.8997,  0.8344],
        [-0.9382, -0.5430]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [-2.8954,  1.9769]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-1.1402, -0.8388]])
tensor([0, 0])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.0683, -0.9701]])
tensor([1, 1])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [-0.5872, -1.9717]])
tensor([0, 0])
--------------------------------------------------
