In [2]:
# !pip install nltk

In [3]:
import torch 
import torch.nn as nn
import torch.optim as optim
import numpy as np 
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk 

In [4]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""


In [5]:
# tokenization 
nltk.download('punkt')
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\lokes\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\lokes\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [6]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\lokes\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [7]:
# tokenize
tokens = word_tokenize(document)

In [8]:
# build vocab 
vocab = {'<unk>':0}

for token in Counter(tokens).keys():
    if token not in vocab:
        vocab[token] = len(vocab)

vocab

{'<unk>': 0,
 'About': 1,
 'the': 2,
 'Program': 3,
 'What': 4,
 'is': 5,
 'course': 6,
 'fee': 7,
 'for': 8,
 'Data': 9,
 'Science': 10,
 'Mentorship': 11,
 '(': 12,
 'DSMP': 13,
 '2023': 14,
 ')': 15,
 'The': 16,
 'follows': 17,
 'a': 18,
 'monthly': 19,
 'subscription': 20,
 'model': 21,
 'where': 22,
 'you': 23,
 'have': 24,
 'to': 25,
 'make': 26,
 'payments': 27,
 'of': 28,
 'Rs': 29,
 '799/month': 30,
 '.': 31,
 'total': 32,
 'duration': 33,
 '?': 34,
 '7': 35,
 'months': 36,
 'So': 37,
 'becomes': 38,
 '799': 39,
 '*': 40,
 '=': 41,
 '5600': 42,
 'approx': 43,
 'syllabus': 44,
 'mentorship': 45,
 'program': 46,
 'We': 47,
 'will': 48,
 'be': 49,
 'covering': 50,
 'following': 51,
 'modules': 52,
 ':': 53,
 'Python': 54,
 'Fundamentals': 55,
 'libraries': 56,
 'Analysis': 57,
 'SQL': 58,
 'Maths': 59,
 'Machine': 60,
 'Learning': 61,
 'ML': 62,
 'Algorithms': 63,
 'Practical': 64,
 'MLOPs': 65,
 'Case': 66,
 'studies': 67,
 'You': 68,
 'can': 69,
 'check': 70,
 'detailed': 71,
 

In [9]:
vocab['about']

132

In [10]:
input_sentences = document.split('\n')

In [11]:
def text_to_indices(sentence, vocab):

    numerical_sentence = []

    for token in sentence:
        if token in vocab:
            numerical_sentence.append(vocab[token])
        else:
            numerical_sentence.append(vocab['<unk>'])

    return numerical_sentence

In [12]:
input_numerical_sentences = []

for sentence in input_sentences:
    input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()), vocab))

In [13]:
len(input_numerical_sentences)

78

In [14]:
training_sequence = []

for sentence in input_numerical_sentences:
    for i in range(1, len(sentence)):
        training_sequence.append(sentence[:i+1])
    

In [15]:
word = "hello"
word[:2]

'he'

In [16]:
len_list = []

for sequence in training_sequence:
    len_list.append(len(sequence))

max(len_list)

62

In [17]:
padding_training_sequence = []

for sequence in training_sequence:

    padding_training_sequence.append([0]*(max(len_list) - len(sequence)) + sequence)

In [18]:
[0,0,0] + [1,2,3]

[0, 0, 0, 1, 2, 3]

In [19]:
padding_training_sequence

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  132,
  2],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  132,
  2,
  46],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  223,
  5],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,


In [20]:
padding_training_sequence = torch.tensor(padding_training_sequence, dtype=torch.long)

In [21]:
padding_training_sequence.shape

torch.Size([942, 62])

In [22]:
X = padding_training_sequence[:,:-1]
y = padding_training_sequence[:,:-1]

In [24]:
class CustomDataset(Dataset):

    def __init__(self, X, y):
        self.X = X
        self.y = y 

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [25]:
dataset = CustomDataset(X,y)

In [26]:
len(dataset)

942

In [27]:
dataset[0]

(tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0, 132]),
 tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0, 132]))

In [28]:
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

In [29]:
for input, output in dataloader:
    print(input, output)

tensor([[  0,   0,   0,  ...,  87, 167,  24],
        [  0,   0,   0,  ...,  49, 157,  25],
        [  0,   0,   0,  ...,  31,   0,  69],
        ...,
        [  0,   0,   0,  ...,  90,  23,  85],
        [  0,   0,   0,  ...,  18, 256, 215],
        [  0,   0,   0,  ...,   2, 207,  28]]) tensor([[  0,   0,   0,  ...,  87, 167,  24],
        [  0,   0,   0,  ...,  49, 157,  25],
        [  0,   0,   0,  ...,  31,   0,  69],
        ...,
        [  0,   0,   0,  ...,  90,  23,  85],
        [  0,   0,   0,  ...,  18, 256, 215],
        [  0,   0,   0,  ...,   2, 207,  28]])
tensor([[  0,   0,   0,  ...,   0, 223,   5],
        [  0,   0,   0,  ..., 100, 169, 305],
        [  0,   0,   0,  ...,  99,  27,  34],
        ...,
        [  0,   0,   0,  ..., 174, 144, 175],
        [  0,   0,   0,  ..., 272,  25,  95],
        [  0,   0,   0,  ...,  31, 102, 174]]) tensor([[  0,   0,   0,  ...,   0, 223,   5],
        [  0,   0,   0,  ..., 100, 169, 305],
        [  0,   0,   0,  ...,  99,  27

In [36]:
class LSTMModel(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, 100)
    self.lstm = nn.LSTM(100, 150, batch_first=True)
    self.fc = nn.Linear(150, vocab_size)

  def forward(self, x):
    embedded = self.embedding(x)
    intermediate_hidden_states, (final_hidden_state, final_cell_state) = self.lstm(embedded)
    output = self.fc(final_hidden_state.squeeze(0))
    return output

In [37]:
model = LSTMModel(len(vocab))

In [38]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [39]:
model.to(device)

LSTMModel(
  (embedding): Embedding(311, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=311, bias=True)
)

In [40]:
epochs = 50 
learning_rate = 0.001

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [42]:
# training loop

for epoch in range(epochs):
  total_loss = 0

  for batch_x, batch_y in dataloader:

    batch_x, batch_y = batch_x.to(device), batch_y.to(device)

    optimizer.zero_grad()

    output = model(batch_x)

    target = batch_y[:, -1]

    loss = criterion(output, target)

    loss.backward()

    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 156.4327
Epoch: 2, Loss: 116.1169
Epoch: 3, Loss: 89.9104
Epoch: 4, Loss: 69.6664
Epoch: 5, Loss: 53.1451
Epoch: 6, Loss: 40.9327
Epoch: 7, Loss: 30.9606
Epoch: 8, Loss: 23.5632
Epoch: 9, Loss: 18.1905
Epoch: 10, Loss: 14.0875
Epoch: 11, Loss: 10.5144
Epoch: 12, Loss: 8.1293
Epoch: 13, Loss: 6.0499
Epoch: 14, Loss: 4.7033
Epoch: 15, Loss: 3.7618
Epoch: 16, Loss: 3.0162
Epoch: 17, Loss: 2.4834
Epoch: 18, Loss: 2.1503
Epoch: 19, Loss: 1.8405
Epoch: 20, Loss: 1.5882
Epoch: 21, Loss: 1.4019
Epoch: 22, Loss: 1.2702
Epoch: 23, Loss: 1.1258
Epoch: 24, Loss: 1.0175
Epoch: 25, Loss: 0.9211
Epoch: 26, Loss: 0.8535
Epoch: 27, Loss: 0.7811
Epoch: 28, Loss: 0.7230
Epoch: 29, Loss: 0.6698
Epoch: 30, Loss: 0.6240
Epoch: 31, Loss: 0.5814
Epoch: 32, Loss: 0.5455
Epoch: 33, Loss: 0.5091
Epoch: 34, Loss: 0.4780
Epoch: 35, Loss: 0.4514
Epoch: 36, Loss: 0.4258
Epoch: 37, Loss: 0.3989
Epoch: 38, Loss: 0.3804
Epoch: 39, Loss: 0.3599
Epoch: 40, Loss: 0.3450
Epoch: 41, Loss: 0.3279
Epoch: 42, L

In [66]:
# prediction

def prediction(model, vocab, text):

  # tokenize
  tokenized_text = word_tokenize(text.lower())

  # text -> numerical indices
  numerical_text = text_to_indices(tokenized_text, vocab)

  # padding
  padded_text = torch.tensor([0] * (61 - len(numerical_text)) + numerical_text, dtype=torch.long).unsqueeze(0)

  # send to model
  output = model(padded_text.to(device))

  # predicted index
  value, index = torch.max(output, dim=1)

  # merge with text
  return text + " " + list(vocab.keys())[index]

In [68]:
prediction(model, vocab, "The course follows a monthly")

'The course follows a monthly monthly'

In [69]:
import time

num_tokens = 10
input_text = "hi how are"

for i in range(num_tokens):
  output_text = prediction(model, vocab, input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)

hi how are are
hi how are are are
hi how are are are are
hi how are are are are are
hi how are are are are are are
hi how are are are are are are are
hi how are are are are are are are are
hi how are are are are are are are are are
hi how are are are are are are are are are are
hi how are are are are are are are are are are are


In [ ]:
# Function to calculate accuracy
def calculate_accuracy(model, dataloader, device):
    model.eval()  # Set the model to evaluation mode
    correct = 0
    total = 0

    with torch.no_grad():  # No need to compute gradients
        for batch_x, batch_y in dataloader1:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)

            # Get model predictions
            outputs = model(batch_x)

            # Get the predicted word indices
            _, predicted = torch.max(outputs, dim=1)

            # Compare with actual labels
            correct += (predicted == batch_y).sum().item()
            total += batch_y.size(0)

    accuracy = correct / total * 100
    return accuracy

# Compute accuracy
accuracy = calculate_accuracy(model, dataloader, device)
print(f"Model Accuracy: {accuracy:.2f}%")
