In [1]:
import torch 
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU")

GPU is available
Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU


In [3]:
# using empty
torch.empty(2,3)  # allocates memory 

tensor([[-5.2795e+13,  1.3480e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
# using Zeros 
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# use of seed 
torch.rand(2,3)

tensor([[0.4232, 0.6646, 0.1178],
        [0.4510, 0.3953, 0.5846]])

In [6]:
# use seed 
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [7]:
# using tensors 
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
# other ways 

#arange 
print("using a range -> ",torch.arange(0,10))

#using linspace 
print("using linspace ->\n ",torch.linspace(0,10,10))

# using eye 
print("using eye ->\n ",torch.eye(5))

#using full
print("using full ->\n ",torch.full((3,3),5))

using a range ->  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace ->
  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->
  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->
  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor shapes

In [9]:
x  = torch.tensor(([2,3,1],[4,5,6]))
x

tensor([[2, 3, 1],
        [4, 5, 6]])

In [10]:
x.shape 

torch.Size([2, 3])

In [11]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [14]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types 

In [15]:
x.dtype

torch.int64

In [16]:
# assing datatype 
torch.tensor([1.0,2.0,3.4],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [17]:
x.to(torch.float32)

tensor([[2., 3., 1.],
        [4., 5., 6.]])

# Mathematical operations
1. Scaler operation

In [18]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [19]:
# addition 
x + 2

# substraction 
x - 2 

# division 
x /3

# int division 


# mod 
x%2
# power 
x**2


tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [20]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [21]:
a+b
a-b
a**2

tensor([[0.9938, 0.5723, 0.0501],
        [0.0914, 0.0318, 0.6787]])

In [22]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [23]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [24]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [25]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [26]:
# clamp
torch.clamp(d,min=2,max =3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction operation

In [27]:
e = torch.randint(size=(2,3),low=0,high=10)
e

tensor([[8, 0, 7],
        [0, 0, 9]])

In [28]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e,dim=0)

# sum alog row
torch.sum(e,dim=1)


tensor([15,  9])

## Tensor Operations on GPU

In [29]:
torch.cuda.is_available()

True

In [30]:
device = torch.device('cuda')

In [31]:
# creating a new tensor on GPU 
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [32]:
# moving an existing tensor to GPU 
a = torch.rand(2,3)
a

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])

In [33]:
a.to(device)

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]], device='cuda:0')

In [34]:
import time 

size = 10000

matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")


# move matrix to Gpu 
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result_cpu = torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize()  # Ensure all gpu operations are complete 
gpu_time = time.time() - start_time

print(f"Time on gPU: {gpu_time:.4f} seconds")


# compare results 
print("\nSpeed up (CPU time/ GPU time):",cpu_time / gpu_time)

Time on CPU: 4.8788 seconds
Time on gPU: 0.5483 seconds

Speed up (CPU time/ GPU time): 8.897241411095226


# reshapeing Tensors

In [35]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [37]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
b = torch.rand(2,3,4)
b

tensor([[[0.5635, 0.2734, 0.1240, 0.7792],
         [0.7891, 0.5838, 0.0878, 0.0257],
         [0.9319, 0.8348, 0.8722, 0.0954]],

        [[0.0307, 0.7172, 0.4986, 0.0144],
         [0.7610, 0.4741, 0.5713, 0.1198],
         [0.2450, 0.5691, 0.8353, 0.1892]]])

In [39]:
# permute 
b.permute(2,1,0).shape 

torch.Size([4, 3, 2])

In [40]:
# unsqeeze
# image size 
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [41]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

In [42]:
import numpy as np  

In [43]:
print(np.__version__)

2.3.2


In [44]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [45]:
b = a.numpy()
b

array([1, 2, 3])

In [46]:
torch.from_numpy(b)

tensor([1, 2, 3])

# Autograd

In [47]:
x = torch.tensor(3.0,requires_grad= True)

In [48]:
x

tensor(3., requires_grad=True)

In [49]:
y = x**2 

In [50]:
y

tensor(9., grad_fn=<PowBackward0>)

In [51]:
y.backward()

x.grad

tensor(6.)

In [60]:
x = torch.tensor(3.0,requires_grad= True)
y = x**2
z = torch.sin(y)

In [61]:
x

tensor(3., requires_grad=True)

In [62]:
y

tensor(9., grad_fn=<PowBackward0>)

In [63]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [64]:
z.backward()


In [65]:
x.grad

tensor(-5.4668)

In [66]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [67]:
w = torch.tensor(1.0,requires_grad=True)
b = torch.tensor(0.0,requires_grad=True)

In [68]:
w

tensor(1., requires_grad=True)

In [69]:
b

tensor(0., requires_grad=True)

In [70]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [71]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)